### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by ignatenkobrain** [turicas/rows#193]
```python
======================================================================
ERROR: test_DecimalField (tests.tests_fields.FieldsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brain/git/fedora/python-rows/rows-0.3.0/tests/tests_fields.py", line 203, in test_DecimalField
    with rows.locale_context(locale_name):
  File "/usr/lib64/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/brain/git/fedora/python-rows/rows-0.3.0/rows/localization.py", line 23, in locale_context
    locale.setlocale(category, name)
  File "/usr/lib64/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

======================================================================
ERROR: test_FloatField (tests.tests_fields.FieldsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brain/git/fedora/python-rows/rows-0.3.0/tests/tests_fields.py", line 171, in test_FloatField
    with rows.locale_context(locale_name):
  File "/usr/lib64/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/brain/git/fedora/python-rows/rows-0.3.0/rows/localization.py", line 23, in locale_context
    locale.setlocale(category, name)
  File "/usr/lib64/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

======================================================================
ERROR: test_IntegerField (tests.tests_fields.FieldsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brain/git/fedora/python-rows/rows-0.3.0/tests/tests_fields.py", line 144, in test_IntegerField
    with rows.locale_context(locale_name):
  File "/usr/lib64/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/brain/git/fedora/python-rows/rows-0.3.0/rows/localization.py", line 23, in locale_context
    locale.setlocale(category, name)
  File "/usr/lib64/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

======================================================================
ERROR: test_PercentField (tests.tests_fields.FieldsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brain/git/fedora/python-rows/rows-0.3.0/tests/tests_fields.py", line 250, in test_PercentField
    with rows.locale_context(locale_name):
  File "/usr/lib64/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/brain/git/fedora/python-rows/rows-0.3.0/rows/localization.py", line 23, in locale_context
    locale.setlocale(category, name)
  File "/usr/lib64/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

======================================================================
ERROR: test_locale_context (tests.tests_localization.LocalizationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brain/git/fedora/python-rows/rows-0.3.0/tests/tests_localization.py", line 41, in test_locale_context
    with locale_context(name):
  File "/usr/lib64/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/brain/git/fedora/python-rows/rows-0.3.0/rows/localization.py", line 23, in locale_context
    locale.setlocale(category, name)
  File "/usr/lib64/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by turicas** [comment]
@ignatenkobrain, thanks for creating the issue.
Did you install all needed locales to run the tests? Brazilian Portuguese is needed.
I've run all tests on Python 3.5.2 and everything worked properly.

**Comment by ignatenkobrain** [comment]
I'm not sure what to install. Basically it's normal python installation.

**Comment by turicas** [comment]
@ignatenkobrain you need the `pt_BR.UTF-8` locale installed on your system to run the tests properly, since there's a localization feature in the library and the tests depend on a different locale (`pt_BR.UTF-8`, in this case).
You can install it by running the following commands:

    echo 'pt_BR.UTF-8 UTF-8' >> /etc/locale.gen
    /usr/sbin/locale-gen

Can you please test it?

**Comment by turicas** [comment]
Note: these commands work on Debian, I don't know about Fedora (is the `locale.gen` is inside the same directory).

**Comment by ignatenkobrain** [comment]
I added `glibc-langpack-pt` and it fixed problem. Thanks for advise!
