### ISSUE TITLE
plugin_json: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 293: ordinal not in range(128)

### ISSUE THREAD

**Issue by ignatenkobrain** [turicas/rows#195]
```python
======================================================================
ERROR: test_import_from_json_retrieve_desired_data (tests.tests_plugin_json.PluginJsonTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/builddir/build/BUILD/rows-0.3.0/tests/tests_plugin_json.py", line 72, in test_import_from_json_retrieve_desired_data
    table_1 = rows.import_from_json(self.filename)
  File "/builddir/build/BUILD/rows-0.3.0/rows/plugins/plugin_json.py", line 40, in import_from_json
    json_obj = json.load(fobj, encoding=encoding)
  File "/usr/lib/python3.5/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 293: ordinal not in range(128)
======================================================================
ERROR: test_import_from_json_uses_create_table (tests.tests_plugin_json.PluginJsonTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/builddir/build/BUILD/rows-0.3.0/tests/tests_plugin_json.py", line 88, in test_import_from_json_uses_create_table
    **kwargs)
  File "/builddir/build/BUILD/rows-0.3.0/rows/plugins/plugin_json.py", line 40, in import_from_json
    json_obj = json.load(fobj, encoding=encoding)
  File "/usr/lib/python3.5/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 293: ordinal not in range(128)
----------------------------------------------------------------------
```

I didn't look into code, but I think you need to use `codec.open()` instead of `open()`

**Comment by turicas** [comment]
Which Python version are you using (`python --version`)? Which packages are installed in your environment (`pip freeze`)?
All the tests are passing here on Python 2.7.11 and Python 3.5.2.

**Comment by ignatenkobrain** [comment]
@turicas it's Python 3.5. But it's executed with `LC_ALL=C`. Basically it doesn't support unicode unless you explicitly specify it.

`get_filename_and_fobj()` uses `open()` which using ASCII charset when `LC_ALL=C`.
