### ISSUE TITLE
Installation failing

### ISSUE THREAD

**Issue by ellisonleao** [turicas/rows#212]
Getting a import error after installing it via pip (`pip install rows`).

I am using Python 3.6.0

```
❯ rows
Traceback (most recent call last):
  File "/Users/ellison/.virtualenvs/rows/bin/rows", line 11, in <module>
    load_entry_point('rows', 'console_scripts', 'rows')()
  File "/Users/ellison/.virtualenvs/rows/lib/python3.6/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/ellison/.virtualenvs/rows/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/Users/ellison/.virtualenvs/rows/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/Users/ellison/.virtualenvs/rows/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/ellison/Code/rows/rows/cli.py", line 31, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

**Comment by ellisonleao** [comment]
Nevermind, just saw that the cli is not coming with the initial version
