### ISSUE TITLE
Error while trying to use rows on mac for the first time

### ISSUE THREAD

**Issue by zecafig** [turicas/rows#231]
(.turicas) white-rabbit:turicas josefigueiredo$ rows convert todasolimpiadas.csv todas.sqlite
Traceback (most recent call last):
  File "/Users/josefigueiredo/.turicas/bin/rows", line 7, in <module>
    from rows.cli import cli
  File "/Users/josefigueiredo/.turicas/lib/python3.5/site-packages/rows/cli.py", line 36, in <module>
    from rows.utils import (detect_source, export_to_uri, import_from_source,
  File "/Users/josefigueiredo/.turicas/lib/python3.5/site-packages/rows/utils.py", line 31, in <module>
    import magic
  File "/Users/josefigueiredo/.turicas/lib/python3.5/site-packages/magic.py", line 61, in <module>
    _open = _libraries['magic'].magic_open
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__
    func = self.__getitem__(name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, magic_open): symbol not found
(.turicas) white-rabbit:turicas josefigueiredo$

**Comment by zecafig** [comment]
Installing only rows[cli] and rows[html], without installing [detect], the library is working fine. 
Very good job @turicas.
