### ISSUE TITLE
Getting Unicode Decode Error

### ISSUE THREAD

**Issue by rjdp** [turicas/rows#247]
>>> import rows
>>> cities = rows.import_from_csv('test.csv')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rajdeepsharma/.virtualenvs/charenc/lib/python2.7/site-packages/rows/plugins/plugin_csv.py", line 71, in import_from_csv
    return create_table(reader, meta=meta, *args, **kwargs)
  File "/Users/rajdeepsharma/.virtualenvs/charenc/lib/python2.7/site-packages/rows/plugins/utils.py", line 142, in create_table
    sample_rows = list(table_rows)
  File "/Users/rajdeepsharma/.virtualenvs/charenc/lib/python2.7/site-packages/unicodecsv/py2.py", line 128, in next
    for value in row]
UnicodeDecodeError: 'utf8' codec can't decode byte 0xcc in position 0: invalid continuation byte

**Comment by turicas** [comment]
Hi. The default encoding is `utf-8`. If your file is not in this encoding you must pass the `encoding` parameter.
Closing this issue since it does not seem to be a bug.
