### ISSUE TITLE
"import magic" errors out on macOS

### ISSUE THREAD

**Issue by rjdp** [turicas/rows#248]
>>> import magic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rajdeepsharma/.virtualenvs/charenc/lib/python2.7/site-packages/magic.py", line 61, in <module>
    _open = _libraries['magic'].magic_open
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, magic_open): symbol not found

**Comment by rjdp** [comment]
ok I did not have libmagic installed, I did `brew install libmagic` now it works 👍 , may be when install file-magic should have errored out saying the dependency `libmagic` is missing, thanks

**Comment by rjdp** [comment]
file-magic dont seem to be as perfect  chardet as for one of my csv file 
*output from filemagic*: ```FileMagic(mime_type='text/plain', encoding='unknown-8bit', name='Non-ISO extended-ASCII text, with very long lines, with CRLF line terminators')```

**output from chardet* :  ```{'confidence': 0.8184309481349372, 'language': 'Greek', 'encoding': 'Windows-1253'}```

chardet's output was very helpful while decoding the file.

**Comment by turicas** [comment]
@rjdp, for text files chardet could be better detecting the file type, but there are some cases in which chardet wrongly detects an encoding - for this reason I prefer to use file-magic. Note that currently only the command-line interface is using file-magic to automatically detect file types.
I'm going to reopen this issue because the documentation about this part is missing.

**Comment by turicas** [comment]
@cuducos, could you please check if information provided here solves your problem also?

**Comment by rjdp** [comment]
@turicas do you have cases where `chardet` predicts wrongly but file-magic does predict correctly, this knowledge will be helpful for me, I just want you to know I am currently using `cchardet` which seems to be ~40x faster than `chardet` as it uses `c` extension.

**Comment by rjdp** [comment]
oh I understand now, my program expects only text csv files so I am safe guess, @turicas but as `rows` will also deal with text CSVs will it not be better to use `cchardet` instead of `file` ?

**Comment by turicas** [comment]
@rjdp, You can see on this video I made (it's in Portuguese but you can understand the code): https://youtu.be/BTMj5bDXByc?t=412 (look the code history also)
I still need to figure out the best options on detection (was thinking in creating a library to deal with it, which would use chardet/cchardet and file-magic, in the best cases for each one).

**Comment by rjdp** [comment]
@turicas in case of text files, when will chardet/cchardet fail to predict correctly and file-magic predicts correctly?

**Comment by turicas** [comment]
@rjdp, I don't have this information in details for you. Look the example in the video, check the mime types supported by `file` and do your tests. ;)

**Comment by cuducos** [comment]
> @cuducos, could you please check if information provided here solves your problem also?

Yep, it did. I mean… I had to create a bare virtualenv (no site packages) in addition to `brew install libmagic`, but this fixed the issue.
