### ISSUE TITLE
Tests failing with Python 3.7 

### ISSUE THREAD

**Issue by williamjmorenor** [turicas/rows#283]
Hello, in the update to python3.7 rows is failint test with the message:

FAIL: rows.Table.__add__ should be constant time
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/rows-0.3.1/tests/tests_table.py", line 318, in test_table_add_time
    self.assertTrue(0.2 * mean > stdev)
AssertionError: False is not true
----------------------------------------------------------------------
Ran 157 tests in 0.874s
FAILED (failures=1)
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.KIoK0X (%check)
    Bad exit status from /var/tmp/rpm-tmp.KIoK0X (%check)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/util.py", line 582, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
mockbuild.exception.Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target noarch --nodeps /builddir/build/SPECS/python-rows.spec

The issue is with the command

nosetests-3.7 -v -e tests_plugin_parquet -e tests_plugin_xlsx -e test_local_file_sample_size -e tests_plugin_json

References:
- Koji Build: https://koji.fedoraproject.org/koji/taskinfo?taskID=27753583
 Build Log: https://kojipkgs.fedoraproject.org//work/tasks/3583/27753583/build.log

**Comment by turicas** [comment]
The tests are currently passing for Python 3.5 to 3.13 (only 2.7 still need some work). Could you please check again? Just run `make test-py37` (will build a container and run `pytest`).
