### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by marcelodcp** [turicas/rows#310]
We I try to do :
rows convert  http://www.bol.com.br  test.csv

I have this log:
IndexError: list index out of range

Can you help me?

Full log:

Traceback (most recent call last):
  File "/usr/bin/rows", line 11, in <module>
    load_entry_point('rows==0.3.1', 'console_scripts', 'rows')()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/rows/cli.py", line 104, in convert
    verify_ssl=verify_ssl)
  File "/usr/lib/python2.7/dist-packages/rows/cli.py", line 52, in _import_table
    encoding=encoding, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/rows/utils.py", line 285, in import_from_uri
    return import_from_source(source, default_encoding, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/rows/utils.py", line 270, in import_from_source
    table = import_function(source.uri, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/rows/plugins/plugin_html.py", line 70, in import_from_html
    table = tables[index]
IndexError: list index out of range

**Comment by turicas** [comment]
The page http://www.bol.com.br does not have a `<table>` inside it. This conversion tool will only work for files/URLs which contains tables. Try with another page, like:
```bash
rows convert https://brasil.io/dataset/genero-nomes/nomes nomes-page-1.csv
```

**Comment by marcelodcp** [comment]
Ok, thanks!
