### ISSUE TITLE
Insufficient dependencies for pdf module

### ISSUE THREAD

**Issue by augusto-herrmann** [turicas/rows#311]
When I try to install rows along with the pdf module, I get an error.

## How to reproduce

```
$ cd /tmp
/tmp$ mkdir rows-test
/tmp$ cd rows-test
/tmp/rows-test$ python3 -m venv pyenv
/tmp/rows-test$ source pyenv/bin/activate
(pyenv) /tmp/rows-test$ pip3 install rows[pdf]
Collecting rows[pdf]
  Using cached https://files.pythonhosted.org/packages/f5/01/33aca7061ea7cb2ead54a35fb446259d6ba12ff100bb7e5a9a4d81e7db96/rows-0.4.1-py2.py3-none-any.whl
Collecting pathlib (from rows[pdf])
  Using cached https://files.pythonhosted.org/packages/ac/aa/9b065a76b9af472437a0059f77e8f962fe350438b927cb80184c32f075eb/pathlib-1.0.1.tar.gz
Collecting six (from rows[pdf])
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting unicodecsv (from rows[pdf])
  Using cached https://files.pythonhosted.org/packages/6f/a4/691ab63b17505a26096608cc309960b5a6bdf39e4ba1a793d5f9b1a53270/unicodecsv-0.14.1.tar.gz
Collecting cached-property; extra == "pdf" (from rows[pdf])
  Using cached https://files.pythonhosted.org/packages/3b/86/85c1be2e8db9e13ef9a350aecd6dea292bd612fa288c2f40d035bb750ded/cached_property-1.5.1-py2.py3-none-any.whl
Collecting pymupdf; extra == "pdf" (from rows[pdf])
  Using cached https://files.pythonhosted.org/packages/40/5e/1c94fe133301ab7b1c92f193ed4b3bb6e2fbb48ef5c0ac469f9f2bdd7e5c/PyMuPDF-1.14.11-cp36-cp36m-manylinux1_x86_64.whl
Building wheels for collected packages: pathlib, unicodecsv
  Running setup.py bdist_wheel for pathlib ... error
  Complete output from command /tmp/rows-test/pyenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tpx2s2bh/pathlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp_8wdsz50pip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for pathlib
  Running setup.py clean for pathlib
  Running setup.py bdist_wheel for unicodecsv ... error
  Complete output from command /tmp/rows-test/pyenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tpx2s2bh/unicodecsv/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmptxyp18rfpip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for unicodecsv
  Running setup.py clean for unicodecsv
Failed to build pathlib unicodecsv
Installing collected packages: pathlib, six, unicodecsv, cached-property, pymupdf, rows
  Running setup.py install for pathlib ... done
  Running setup.py install for unicodecsv ... done
Successfully installed cached-property-1.5.1 pathlib-1.0.1 pymupdf-1.14.11 rows-0.4.1 six-1.12.0 unicodecsv-0.14.1
```

Then run the command for converting PDFs:

```
(pyenv) /tmp/rows-test$ rows pdf-to-text test.pdf
Traceback (most recent call last):
  File "/tmp/rows-test/pyenv/bin/rows", line 7, in <module>
    from rows.cli import cli
  File "/tmp/rows-test/pyenv/lib/python3.6/site-packages/rows/cli.py", line 31, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

However, if I manually install the following dependencies and repeat the command, it works:

```
(pyenv) /tmp/rows-test$ pip3 install click requests requests_cache tqdm
```

Maybe these modules are missing from the declared dependencies?

**Comment by turicas** [comment]
To use the PDF plugin *and* the command-line interface you must also install `rows[cli]` (which installs `click` and other libraries).
If you think it should be more explicit in the documentation, could you please create an issue or PR with the change (just need to change the markdown file inside `docs/`)?

**Comment by augusto-herrmann** [comment]
[Sure](https://github.com/turicas/rows/pull/312).

But, anyway, should just running `pip install rows[pdf]` generate errors like that? Is it expected behaviour?

Somehow I don't think it should, as you can also use the PDF module as a library, so I understand that the CLI is not something you necessarily have to install first.
