### ISSUE TITLE
Python 3.7.0 error on import rows

### ISSUE THREAD

**Issue by engrogerio** [turicas/rows#348]
On Python 3.7.0, windows :
```
>>> import rows
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rsilva\source\aws\.env\lib\site-packages\rows\__init__.py", line 22, in <module>
    import rows.plugins as plugins
  File "C:\Users\rsilva\source\aws\.env\lib\site-packages\rows\plugins\__init__.py", line 20, in <module>
    from . import plugin_csv as csv  # NOQA
  File "C:\Users\rsilva\source\aws\.env\lib\site-packages\rows\plugins\plugin_csv.py", line 34, in <module>
    unicodecsv.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long
```

**Comment by engrogerio** [comment]
It looks like rows is trying `unicodecsv.field_size_limit(9223372036854775807)` when the maximum value allowed is 2147483647.

**Comment by engrogerio** [comment]
Repeated issue #306
