### ISSUE TITLE
After pip install, import immediately breaks in interpreter due to plugin error with sys.maxsize

### ISSUE THREAD

**Issue by camphil-kalderos** [turicas/rows#355]
>>> import rows
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\cphil\Anaconda3\lib\site-packages\rows\__init__.py", line 22, in <module>
    import rows.plugins as plugins
  File "C:\Users\cphil\Anaconda3\lib\site-packages\rows\plugins\__init__.py", line 20, in <module>
    from . import plugin_csv as csv  # NOQA
  File "C:\Users\cphil\Anaconda3\lib\site-packages\rows\plugins\plugin_csv.py", line 34, in <module>
    unicodecsv.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long

**Comment by turicas** [comment]
Duplicate of #306.
