### ISSUE TITLE
Error after installation and run convert

### ISSUE THREAD

**Issue by NicolasPio** [turicas/rows#97]
I install rows with pip and run 'convert'.
I run rows in docker container with Debian Jessie, I already tried in several ways

Error return:
```
Traceback (most recent call last):
  File "/usr/local/bin/rows", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rows/cli.py", line 50, in convert
    table = import_from_uri(source)
  File "/usr/local/lib/python2.7/dist-packages/rows/utils.py", line 176, in import_from_uri
    raise ValueError('Plugin (import) "{}" not found'.format(plugin_name))
ValueError: Plugin (import) "html;charset=utf-8" not found
```

**Comment by turicas** [comment]
This bug was already identified and fixed (see #86) but it is not available on PyPI yet since the fix is on [develop](https://github.com/turicas/rows/tree/develop) branch and will be available on PyPI only in the next version (see [milestone 0.2.0](https://github.com/turicas/rows/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Version+0.2.0%22) for more details).

You can install the version in `develop` directly by running:

```bash
pip install --upgrade git+https://github.com/turicas/rows.git@develop
```

As a work-around you can download the file manually and then run `rows convert` with the local URI, for example:

```bash
wget -O myfile.html http://some-url/
rows convert myfile.html another-file.csv
```
